# Generated by Django 5.0.1 on 2024-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
